# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import first_service_pb2 as first__service__pb2


class TTSPythonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertTTS = channel.unary_unary(
                '/ttspython.TTSPython/ConvertTTS',
                request_serializer=first__service__pb2.TextMessage.SerializeToString,
                response_deserializer=first__service__pb2.SpeechResponse.FromString,
                )


class TTSPythonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertTTS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSPythonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertTTS': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertTTS,
                    request_deserializer=first__service__pb2.TextMessage.FromString,
                    response_serializer=first__service__pb2.SpeechResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ttspython.TTSPython', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TTSPython(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertTTS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ttspython.TTSPython/ConvertTTS',
            first__service__pb2.TextMessage.SerializeToString,
            first__service__pb2.SpeechResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
